---
- name: Set table suffix
  include: suffix.yml

- name: Add table with indexes
  dynamodb_table:
    state: present
    name: "{{ [item.name, dynamo_db_suffix]|join('-') }}"
    hash_key_name: "{{ item.hash_key | default('id') }}"
    hash_key_type: "{{ item.hash_key_type | default('STRING') }}"
    indexes: "{{ item.indexes| default(omit) }}"
    read_capacity: "{{ item.read_capacity | default(5) }}"
    write_capacity: "{{ item.write_capacity | default(5) }}"
  with_items: "{{ dynamodbs | default([]) }}"
  register: dynamodb_created

- block:
    - name: Wait for tables to settle
      pause:
          minutes: 2

    - name: Configure TTL settings for dynamodb instances
      dynamodb_ttl:
        state: "{{ item.state }}"
        table_name: "{{ [item.name, dynamo_db_suffix]|join('-') }}"
        attribute_name: "{{ item.attribute }}"
      with_items: "{{ dynamodbs_ttl | default([]) }}"

  when: dynamodbs_ttl|default(False)

- block:
    - name: Create our scaling policies
      include: "create-scaling-policies.yml"
      with_items: "{{ dynamodbs_scaling_policies|default([]) }}"
      loop_control:
        loop_var: dynamo_scaling_policy

  when: dynamodbs_scaling_policies|default(False)