---

- name: Create task defintiion
  ecs_taskdefinition:
    family: "{{ appdata.name }}-{{ target}}"
    state: present
#    task_role_arn: "arn:aws:iam::{{ aws_acc_id }}:role/{{ appdata.name }}-{{ target}}"
    containers: "{{ appdata.containers }}"
    volumes: "{{ appdata.volumes| default() | ecs_volume_metadata_trim or omit}}"
  register: ecstask

- block:
    - set_fact:
        nfs_host: "{{ groups['nfs-' + target][0] }}"
    - set_fact:
        nfs_launch_time: "{{ hostvars[nfs_host]['create_time'][0:19]|regex_replace('T|Z', ' ') }}"

    - name: Test that NFS server is older than 6 minutes
      shell: date +'%Y-%d-%m %H:%M:%S'
      register: nfs_ready
      until: ((nfs_ready.stdout|to_datetime) - (nfs_launch_time|to_datetime('%Y-%m-%d %H:%M:%S'))).total_seconds()|int > nfs_wait|default(360)
      retries: 10
      delay: 30

    - name: Ensure symlink nsfdata to data on NFS server
      file:
        src: '/data'
        dest: '/nfsdata'
        state: link
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true

    - name: Create NFS directory shares for service
      file:
        state: directory
        follow: yes
        owner: 999
        path: "{{ item.host.sourcePath | dirname }}"
      with_items: "{{appdata.volumes}}"
      when:
        - appdata.volumes is defined
        - appdata.volumes|count > 0
        - "item.host.createNfsFolder | default('true') | bool"
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true

    - name: Ensure template paths are created
      file:
        state: directory
        follow: yes
        owner: 999
        path: "{{ item.path | dirname }}"
      with_items: "{{appdata.templates}}"
      when: appdata.templates is defined
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true

    - name: Create templates on NFS
      template:
        src: "{{item.sourceTemplate}}"
        dest: "{{item.path}}"
        owner: 999
      with_items: "{{appdata.templates}}"
      when: appdata.templates is defined
      delegate_to: "{{ groups[ 'nfs-' + target ][0] }}"
      become: true


  when: use_ecs_nfs_server|default(False)


- name: Create service definition for task with ELB
  ecs_service:
    state: present
    name: "{{ appdata.name }}-{{ target}}"
    cluster: "{{ appdata.ecs_cluster }}-{{ target}}"
    load_balancers: "{{ appdata.elb.ecs_definition }}"
    role: "{{ appdata.name }}.{{ target }}"
    task_definition: "{{ appdata.name }}-{{ target}}:{{ ecstask.taskdefinition.revision }}"
    desired_count: "{{ appdata.count|default('1') }}"
  register: ecsservice
  when: has_elb

- name: Create service definition for task
  ecs_service:
    state: present
    name: "{{ appdata.name }}-{{ target}}"
    cluster: "{{ appdata.ecs_cluster }}-{{ target}}"
    task_definition: "{{ appdata.name }}-{{ target}}:{{ ecstask.taskdefinition.revision }}"
    desired_count: "{{ appdata.count|default('1') }}"
  register: ecsservice
  when: not has_elb

- block:
    - name: Lookup client group id
      ec2_group_facts:
        filters:
          "tag:Stack": "{{ target }}"
      register: client_sg_id

    - name: Create security group for app
      ec2_group:
        name: "{{ appdata.server_sg.name }}"
        description: "{{ appdata.server_sg.desc }}"
        rules: "{{ appdata.server_sg.ruleset | rules_from_dict(client_sg_id.security_groups, appdata.server_sg.client_sg) }}"
        rules_egress: []
        vpc_id: "{{ vpc_id }}"
      register: server_security_group

    - name: Add tags until 2.2
      ec2_tag:
        resource: "{{ server_security_group.group_id }}"
        state: present
        tags: "{{ vpc.env_tags | combine({'Name': appdata.server_sg.name}) }}"

  when: appdata.server_sg is defined
