---
- block:
    - name: Create security group  for access to shared services
      ec2_group:
        name: "shared-services-{{ opg_data.stack }}"
        description: "shared services {{ opg_data.stack }}"
        rules_egress:
        state: present
        vpc_id: "{{ app_vpc['vpc_id'] }}"
      register: shared_services_sg

    - name: Create jumphost security group
      ec2_group:
        name: "jumphost-{{ opg_data.stack }}"
        description: "{{ item.description }} for {{ opg_data.stack }}"
        rules: "{{ item.ruleset | rules_from_dict() }}"
        state: present
        vpc_id: "{{ app_vpc['vpc_id'] }}"
      with_items: "{{ vpc.security_groups }}"
      when: item.Name == 'jumphost'
      register: jump_sg

    - name: Create cloudfront security group
      ec2_group:
        name: "cloudfront-{{ opg_data.stack }}"
        description: "{{ item.description }} for {{ opg_data.stack }}"
        rules: "{{ item.ruleset | rules_from_dict() }}"
        state: present
        vpc_id: "{{ app_vpc['vpc_id'] }}"

      with_items: "{{ vpc.security_groups }}"
      when: item.Name == 'cloudfront'
      register: cf_sg

    - name: Create jumphost client security group
      ec2_group:
        name: "jumphost-client-{{ opg_data.stack }}"
        description: "jumphost client security group for {{ opg_data.stack }}"
        rules: "{{ [ jump_sg.results | get_sg_id_result ]| make_rules('22', 'tcp', True) }}"
        state: present
        vpc_id: "{{ app_vpc['vpc_id'] }}"
      register: jump_client_sg

- block:
    - name: Create salt master security group
      ec2_group:
        name: "salt-master-{{ opg_data.stack }}"
        description: "salt master security group for {{ opg_data.stack }}"
        rules: "{{  item.ruleset | rules_from_dict([ shared_services_sg.group_id ]) }}"
        state: present
        vpc_id: "{{ app_vpc['vpc_id'] }}"
      with_items: "{{ vpc.security_groups }}"
      when: item.Name == 'salt-master'
      register: salt_master_sg

    - name: Add tags separately till version 2.2
      ec2_tag:
        resource: "{{ item.group_id }}"
        state: present
        tags: "{{ vpc.env_tags }}"
      with_items:
        - "{{ jump_client_sg }}"
        - "{{ jump_sg.results | get_sg_result() }}"
        - "{{ shared_services_sg }}"
        - "{{ salt_master_sg.results | get_sg_result() }}"
